# Generated by Django 5.0.4 on 2024-06-01 19:03

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', editable=False, length=10, max_length=20, prefix='Fourn-', unique=True)),
                ('title', models.CharField(default='untitle fournisseur', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
