# Generated by Django 5.0.4 on 2024-06-02 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_fournisseur_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='supply',
            name='livrer_name',
            field=models.CharField(default='not set', max_length=500),
        ),
        migrations.AddField(
            model_name='supply',
            name='livrer_phone',
            field=models.CharField(default='not set', max_length=500),
        ),
    ]
