# Generated by Django 5.0.4 on 2024-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_fournisseur_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
