# Generated by Django 5.0.4 on 2024-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_product_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/core/core/static/assets/images/new-document.png', upload_to=''),
        ),
    ]
