# Generated by Django 5.0.4 on 2024-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='./core/core/static/assets/images/new-document.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
