# Generated by Django 5.0.4 on 2024-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='action',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
