# Generated by Django 5.0.4 on 2024-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_rename_at_action_date_action_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../new-document.png', upload_to='product_image'),
        ),
    ]
